### ISSUE TITLE
Seeds must be encoded as Rust Strings with u64 size prefixes

### ISSUE THREAD

**Issue by steveluscher** [solana-program/system#7]
Failing test case

```ts
import { getCreateAccountWithSeedInstruction } from "@solana-program/system";
const modernTx = getCreateAccountWithSeedInstruction({
  payer: "11111111111111111111111111111111",
  baseAccount: "11111111111111111111111111111111",
  newAccount: "11111111111111111111111111111111",
  base: "11111111111111111111111111111111",
  seed: 'Hello world',
  amount: 1000000n,
  space: 100n
  programAddress: "11111111111111111111111111111111",
});
console.log(Array.from(modernTx.data).map(byte => byte.toString(16).padStart(2, '0')).join(' '));
/**
 * 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 * 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 * 00 00 00 00 0b 00 00 00 48 65 6c 6c 6f 20 77 6f
 *              ^ 11 (u32) ^H ^e ^l ^l ^o ^_ ^W ^o
 * 72 6c 64 40 42 0f 00 00 00 00 00 64 00 00 00 00
 * ^r ^l ^d
 * 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 * 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 * 00 00 00
 */
```

Missing 4 bytes of padding between the length and the string.

See https://github.com/solana-labs/solana-web3.js/blob/545c43992f555d54fe865788190e14eadd62264d/packages/library-legacy/src/layout.ts#L59

**Comment by steveluscher** [comment]
I'm actually a bit concerned that these length prefixes are variable length integers (7 bits of data + a continuation bit). Need to dig around a bit,

**Comment by steveluscher** [comment]
Oof. OK, this took me way too long to figure out.

Yes, `bincode` encodes with variable length integers but _only_ if enabled.

```rust
let foo: String = "Hello".to_string();
println!(
    "{:?}",
    bincode::options().with_varint_encoding().serialize(&foo)
);
// Ok([5, 72, 101, 108, 108, 111])
```

Ours just produces a `u64` length. I don't know if that implies ‘on 64-bit systems’ but at this point I don't think that matters.

**Comment by lorisleiva** [comment]
Hey @steveluscher, sorry I missed that.

From the shared code snippet, it looks like the bytes are serialised as follow:

- a `u32` prefix giving us the size of the string.
- a `u32` padding (filled with zeros) potentially to ensure byte-alignment.
- the content of the UTF-8 string — which itself doesn't seem to be aligned.

We can achieve this using Kinobi nodes.

Using the `SizePrefixTypeNode` is not enough size it will only give us the first `u32` prefix and not the padding.

<img width="1200" alt="Kinobi Example-1" src="https://github.com/solana-program/system/assets/3642397/674dc2c5-fb4f-4721-8dbd-ad47e354a255">

Using a `u64` also won't work because the System program expects little-endian numbers.

<img width="1200" alt="Kinobi Example u64" src="https://github.com/solana-program/system/assets/3642397/18cb09f1-bf3d-400a-9915-17aa72a42bf0">

In order to get the second `u32` of padding, we can use the `PostOffsetTypeNode` using the `padded` strategy which will push the offset to the right (if a positive offset is provided) and adjust the codec size accordingly.

<img width="1200" alt="Kinobi Example" src="https://github.com/solana-program/system/assets/3642397/69ab8929-106d-4159-98d2-2de99567b5a4">

I hope this helps.

**Comment by steveluscher** [comment]
![wow-indiana-jones](https://github.com/solana-program/system/assets/13243/fb8b9fb8-10f1-4151-9f0f-56b8040e0976)


https://github.com/solana-labs/solana/blob/ad2fa3ceaf0265af177bb961e4301049b9013b16/web3.js/src/token-program.js#L28
